version: '2'
services:
  keeper-postgres:
    container_name: postgres
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres-volume:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
  postgres-volume: {}